In [1]:
import tensorflow as tf

In [2]:
sentences = [
    'I love my dog',
    'I love my cat',
    'You love my dog!',
    'Do you think my dog is amazing?'
    ]

vectorize_layer = tf.keras.layers.TextVectorization()

In [3]:
vectorize_layer.adapt(sentences)
vocab = vectorize_layer.get_vocabulary(include_special_tokens=False )

In [4]:
for index, word in enumerate(vocab):
    print(f"{index}: {word}")

0: my
1: love
2: dog
3: you
4: i
5: think
6: is
7: do
8: cat
9: amazing


In [5]:
sample = "i love my dog"
sequence = vectorize_layer(sample)

print(sequence)

tf.Tensor([6 3 2 4], shape=(4,), dtype=int64)


In [7]:
sentence_dataset = tf.data.Dataset.from_tensor_slices(sentences)
sequences = sentence_dataset.map(vectorize_layer)

for sentence, sequence in zip(sentences, sequences):
    print(f"{sentence} --> {sequence}")

I love my dog --> [6 3 2 4]
I love my cat --> [ 6  3  2 10]
You love my dog! --> [5 3 2 4]
Do you think my dog is amazing? --> [ 9  5  7  2  4  8 11]


In [9]:
sequence_post = vectorize_layer(sentences)
print('INPUT:')
print(sentences)
print()

print('OUTPUT:')
print(sequence_post)

INPUT:
['I love my dog', 'I love my cat', 'You love my dog!', 'Do you think my dog is amazing?']

OUTPUT:
tf.Tensor(
[[ 6  3  2  4  0  0  0]
 [ 6  3  2 10  0  0  0]
 [ 5  3  2  4  0  0  0]
 [ 9  5  7  2  4  8 11]], shape=(4, 7), dtype=int64)


In [11]:
sequences_post_trunc = tf.keras.utils.pad_sequences(sequences, maxlen=5, padding='pre')
print('INPUT:')
[print(sequence.numpy()) for sequence in sequences]
print()

print('OUTPUT:')
print(sequences_post_trunc)


INPUT:
[6 3 2 4]
[ 6  3  2 10]
[5 3 2 4]
[ 9  5  7  2  4  8 11]

OUTPUT:
[[ 0  6  3  2  4]
 [ 0  6  3  2 10]
 [ 0  5  3  2  4]
 [ 7  2  4  8 11]]


In [12]:
# Set the layer to output a ragged tensor
vectorize_layer = tf.keras.layers.TextVectorization(ragged=True)

# Compute the vocabulary
vectorize_layer.adapt(sentences)

# Apply the layer to the sentences
ragged_sequences = vectorize_layer(sentences)

# Print the results
print(ragged_sequences)

<tf.RaggedTensor [[6, 3, 2, 4], [6, 3, 2, 10], [5, 3, 2, 4], [9, 5, 7, 2, 4, 8, 11]]>


In [13]:
# Pre-pad the sequences in the ragged tensor
sequences_pre = tf.keras.utils.pad_sequences(ragged_sequences.numpy())

# Print the results
print(sequences_pre)

[[ 0  0  0  6  3  2  4]
 [ 0  0  0  6  3  2 10]
 [ 0  0  0  5  3  2  4]
 [ 9  5  7  2  4  8 11]]


In [14]:
# Try with words that are not in the vocabulary
sentences_with_oov = [
    'i really love my dog',
    'my dog loves my manatee'
]

# Generate the sequences
sequences_with_oov = vectorize_layer(sentences_with_oov)

# Print the integer sequences
for sentence, sequence in zip(sentences_with_oov, sequences_with_oov):
  print(f'{sentence} ---> {sequence}')

i really love my dog ---> [6 1 3 2 4]
my dog loves my manatee ---> [2 4 1 2 1]
